### ISSUE TITLE
Voron V0 Sherpa Revo Cowl - Thin Wall Causing Gaps

### ISSUE THREAD

**Issue by falo2k** [jlas1/Klicky-Probe#108]
Slicing the sherpa revo cowl for the V0 keeps creating this gappy thin wall area along the edge that adjoins the mount.  It looks like it's been cut a touch more than the sherpa dragon cowling if I compare the two 

![image](https://user-images.githubusercontent.com/1392563/168871364-ced538b3-e9e3-4a97-ba8f-9d5e49800e41.png)

![image](https://user-images.githubusercontent.com/1392563/168872018-ef0bd611-37eb-48ca-ae00-212d22f6cb52.png)

**Comment by jlas1** [comment]
Thanks corrected in main file.

**Comment by falo2k** [comment]
Perfect.  Cheers for the quick turnaround!
