### ISSUE TITLE
KlickyNG_UnklickyBFP_v1_Pin.stl

### ISSUE THREAD

**Issue by leesafur** [jlas1/Klicky-Probe#125]
The walls that hold the magnet are too thin to reliably hold the magnet in place on the pin. This causes the two thin walls to flex outwards and results in interference when inserting the pin into the main body.

**Comment by jlas1** [comment]
sorry for the long wait, it's hard to solve this issue, you can scrape a bit of the extra plastic after inserting the magnet, should make it work better.
