### ISSUE TITLE
KlickSwipe dosen't fit new MG90s

### ISSUE THREAD

**Issue by thbl** [jlas1/Klicky-Probe#133]
it seams that the new MG90s is shorter, could you make your mount fit them ? :)
Sadly i don't have the skills :i but here are cads for them
https://grabcad.com/library/towerpro-mg90s-micro-servo-1
@jlas1 

Also would it not be better to use some kind of rods instead of PTFE ?

**Comment by jlas1** [comment]
Can you measure yours, i purchased mines pretty recently.

**Comment by thbl** [comment]
@jlas1 also orginals ? as you can see on their website they are lower (do you need any other measurements then on this link?)
https://www.towerpro.com.tw/product/mg90s-3/

**Comment by jlas1** [comment]
It should be ok, have you tried to print and fit it
where was your difficulty?

**Comment by jlas1** [comment]
Also, you can use a metal pin, most people has PTFE tubes and they also work fine, so YMMV.
