### ISSUE TITLE
Missing CAD for switchwire parts

### ISSUE THREAD

**Issue by yuripolak** [jlas1/Klicky-Probe#138]
Found only the step files for the Klicky and Klick NG parts, but nothing on the servo parts, arms, etc
Woulkd like to do minor tweaks since my SW carriage is not stock

**Comment by jlas1** [comment]
here you have all the klicky parts https://github.com/jlas1/Klicky-Probe/blob/main/CAD/KlickyProbe_v2_v59.step
The switchwire has a assembly within where the parts are.
