### ISSUE TITLE
Pin number on SKR board

### ISSUE THREAD

**Issue by Leafguy16** [jlas1/Klicky-Probe#14]
The connector mentioned to plug into is pin 1.27 not 1.28 for SKR 1.3. 
It is also possible to just leave the wiring for the inductive probe and plug in the klicky at the tool head to use the existing pin set and connector.

**Comment by jlas1** [comment]
You are right, the documentation should make that clearer, i'll update it.

**Comment by jlas1** [comment]
clarified, thank you.
