### ISSUE TITLE
Back magnet in probe is 0.2mm higher than 2 other magnets (that are attached to microswitch)

### ISSUE THREAD

**Issue by rstanislav** [jlas1/Klicky-Probe#151]
Looking at the sliced part i can see that back magnet is 1 layer higher (0.2mm), so when assembled it causes very small tilt by 0.2mm, is it supposed to be like this ?(on the left side of the photo you can see there is 2 layers of wall already around magnet, and on the right - only 1 layer of wall)
![photo_2022-09-19_15-09-49](https://user-images.githubusercontent.com/1781042/191014082-51e783d2-5acf-42e8-9382-56777151668e.jpg)

**Comment by jlas1** [comment]
you are correct, it was 0.113 mm lower, corrected that in CAD, when i push that version, it will be correct.
With that said, the glue should prevent it from being too deep inside.
