### ISSUE TITLE
[FR] Allow `QUAD_GANTRY_LEVEL` to take arguments for the x-y extents

### ISSUE THREAD

**Issue by kubark42** [jlas1/Klicky-Probe#153]
A clever bit of code landed at https://gist.github.com/ChipCE/95fdbd3c2f3a064397f9610f915f7d02?fbclid=IwAR0rDS-75BpV0W0z_s2fxm3JsC6ik6PmdErTma460Pjyd_sYOU06-Rrkfxk. A good description is here: https://3dprintbeginner.com/faster-klipper-bed-probing-macro/

In a nutshell, this does a bed calibration only for the area which will be printed. I would like to do the same, especially because my bed bows quite a lot at high temperatures and so I want to have the calibration stay close to my printing area. It turns out it gets thrown off quite badly when it tests the four corners of the bowed bed.

Rather than clobber some of the Klicky klipper macros, as recommended by some of the comments, it would be nice if instead Klippy supported this directly.

**Comment by jlas1** [comment]
Your solution is the best one, it comments out the bed_calibrate macro rename and setup a new one.
I would just include that file outside klicky-probe.cfg, that way an update won't reset that include.

Can't support all the variations of this setup out there.

Thanks for the issue, hope it's running great with your changes
