### ISSUE TITLE
Safe Z doesn't appear to be working on an x/y home

### ISSUE THREAD

**Issue by simpat1zq** [jlas1/Klicky-Probe#154]
Voron 2.4R2. Before I setup the Klicky macros, I was using safe_z_home, which is now commented out per the instructions. 

However, when I do an x/y home, it is not raising the z, which can potentially cause issues if the nozzle is close to the bed. How do I get that feature back where it raises the z when homing x/y?

Also, if I just home Z, it raises the gantry, does an x/y home, and then a z home. So that works the way it should. However, if I turn the motors off, it _should_ forget the coordinates, but that doesn't appear to happen. Even after turning the motors off, if I do a Z home, it does the x/y home without raising the z. When the motors turn off the printer should assume it no longer knows where the toolhead is, and that doesn't appear to be happening when using the Klicky macros.

**Comment by jlas1** [comment]
Can you check the latest macro version and advise if the bug is still there?
also, please include your klicky-variables.cfg

**Comment by jlas1** [comment]
should be solved now, if necessary please reopen.

**Comment by Eiranya** [comment]
> should be solved now, if necessary please reopen.

I used Latest macro,if the xyz axes are already homed,run the full G28 command x/y axes will directly goint to home without raising the z,but if it close to the heatbed  when toolhead run to z endstop position the toolhead will hit the z endstop. Moves the Z to safe_z distance only on the first G28 after motors losing power.
