### ISSUE TITLE
KlickyNG_Probe_body includes impossible bridge / prints in thin air

### ISSUE THREAD

**Issue by ChaosBlades** [jlas1/Klicky-Probe#155]
KlickyNG_Probe_body prints in thin air. I tried to solve this problem in CAD to get it to print a proper bridge using some tricks I know but it refuses to cooperate. Keeps trying to print the circle parameter even with a break away bridge over the hole and squaring the bridge.
![Screenshot from 2022-09-26 23-36-22](https://user-images.githubusercontent.com/7530545/192426251-ffab5560-3c66-4946-b387-1156f73f7097.png)
![Screenshot from 2022-09-26 23-38-04](https://user-images.githubusercontent.com/7530545/192426258-cb809d8d-2fa0-45d5-9fa4-2a44764e9fc2.png)
The only "solution" I found was to enable `Print Settings > No perimeters on bridge areas > Keep only bridges` in SuperSlicer but that leaves a couple of messy areas on the outer perimeter and isn't exactly a user friendly "solution".
![Screenshot from 2022-09-27 00-03-55](https://user-images.githubusercontent.com/7530545/192429445-895f81ae-0f18-4ed9-a8fd-951f5edb90b9.png)
The only thing I can think of is to split the body on this face then make some holes and a peg and superglue the peg in to hold the pieces togeather. However this is NG (No Glue). So that would just be silly.

**Comment by jlas1** [comment]
I have a correction for this now, needs to push that.
