### ISSUE TITLE
I want to change the position of the probe to X direction in and Y direction out

### ISSUE THREAD

**Issue by caogongzi** [jlas1/Klicky-Probe#156]
Now I have a problem. When taking the probe, my machine enters in the Y direction and then exits in the Y direction. I want to enter in the X direction and exit in the Y direction, just like when releasing the probe, it enters in the Y direction and exits in the X direction. This has a good effect on taking the probe and can reduce many unnecessary friction and vibration.

**Comment by jlas1** [comment]
Did you find the solution? The current move system needs to be revamped.
You should leave the attachmove_xyz as they are and set attachmove2_x to 40 or -40.
