### ISSUE TITLE
klicky-macros.cfg: Probe positions are truncated to nearest int (why???)

### ISSUE THREAD

**Issue by idonasch** [jlas1/Klicky-Probe#159]
In klicky-macros.cfg  all references to docklocation_* are cast/filtered to the nearest integer. My dock was off by 0.4mm which caused the attach_probe to fail. The probe always was skewed by a couple degrees and didn't made contact.
Is there a reason that I might have missed? Wouldn't round() be more appropriate if conversion is needed at all?
Anyways I would recommend to do any necessary conversions up in the {% set  ... %} section.

I had to pry the mount over by 0.5mm to get it working.

**Comment by jlas1** [comment]
I'll check how hard is to correct

**Comment by jcfain** [comment]
Just popping in to say I noticed this last night and I agree it should not be casting to an int. Luckily my dock landed close enough to a whole number (43.15) where it still works.
