### ISSUE TITLE
Error in Klicky macro.cfg

### ISSUE THREAD

**Issue by BOAndy1985** [jlas1/Klicky-Probe#165]
Homen in z is no longer possible with the new version of macro.  The error says to home x and y first before going to the dock

**Comment by khumarahn** [comment]
Same here, I think
```
14:23:07  $ G28
14:23:07  // No axis homed
14:23:07  // moving to a safe Z distance
14:23:07  // X or Y not homed, forcing full G28
14:23:07  // Homing X
14:23:07  // Homing Y
14:23:07  // Homing Z
14:23:07  // probe: TRIGGERED
14:23:12  !! Error evaluating 'gcode_macro Dock_Probe:gcode': CommandError: Must Home X, Y and Z Axis First!
14:23:12  !! Error evaluating 'gcode_macro Dock_Probe:gcode': CommandError: Must Home X, Y and Z Axis First!
​```

**Comment by khumarahn** [comment]
I guess that 
```
variable_dock_on_zhome:       True    # docks the probe on Z Homing if not necessary (avoids hitting the bed on some printers                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                               
variable_bypass_probe_docking:        False
```
the procedure is to dock the probe if unnecessary for Z homing, but docking requires Z already homed

**Comment by khumarahn** [comment]
Also I wonder what `variable_bypass_probe_docking` is?..

**Comment by BOAndy1985** [comment]
The funny thing is you do home y and x and then qgl which of course doesn't work z homen

**Comment by BOAndy1985** [comment]
khumarahn
variable_dock_on_zhome: false

**Comment by khumarahn** [comment]
> khumarahn variable_dock_on_zhome: false

yeap, figured that out too. But it is still a bug

**Comment by BOAndy1985** [comment]
What other error did you find?

**Comment by khumarahn** [comment]
Just the original one

**Comment by jlas1** [comment]
> Also I wonder what `variable_bypass_probe_docking` is?..

It's to allow an easier migration to Voron TAP probe

**Comment by jlas1** [comment]
> Homen in z is no longer possible with the new version of macro. The error says to home x and y first before going to the dock

can you enable debug on klicky variables and paste the console here?

**Comment by jlas1** [comment]
I think i found the bug, can you check the last version of the macros.

**Comment by jlas1** [comment]
As it should be correct, i'm closing this issue, if it happens again, it can be reopened.

**Comment by khumarahn** [comment]
Thanks a lot! Looks like it worked, will watch out
