### ISSUE TITLE
Possibility for retrying on attachement failure?

### ISSUE THREAD

**Issue by Nils-Hoffmann** [jlas1/Klicky-Probe#168]
Attaching the probe sometimes fails for me with the Klicky NG probe, as the probe clicks in place such that the two connecting magnets dont touch. Would it be possible to retry attachment on failure by first docking the (not quite properly attached probe) again?

**Comment by jlas1** [comment]
It could be done, but i see little gains and a lot of problems.
You may solve the odd docking issue, but you are asking the toolhead to do another round of moves after it already detected an issue, that may break things.
It's preferable to stop and let the operator correct the error, then resume.
