### ISSUE TITLE
Probe Attach Failed

### ISSUE THREAD

**Issue by deathfrombelow** [jlas1/Klicky-Probe#18]
First time I homed z and it picked up the probe, undocked, but then stopped and gave me this: !! Error evaluating 'gcode_macro SetProbeState:gcode': CommandError: Probe attach failed!  But the probe is attached.

Is this possibly a signal issue?  Because when testing the probe signal (query_probe) I could not get it to work properly.  I have an octopus board and for prior induction probe, I split power to probe port (PB7) and signal to diag7 port (PG15) with diode.  Klicky did not work on PG15, so I switched it back to the probe port PB7, but it also did not work.  Both ports I used with and without the pull up (^) with no difference.  It was either always triggered or always open.  

EDIT: It was signal issue.  I had continuity issues from the magnets not quite contacting each other, fixed by trimming wiring insulation where it bends.

**Comment by jlas1** [comment]
Thanks for the feedback
