### ISSUE TITLE
No adaptation for Mini Stealthburner

### ISSUE THREAD

**Issue by rochford77** [jlas1/Klicky-Probe#192]
Looking into options for the voron 0.2 and the new mini-stealthburner.

**Comment by cereal7802** [comment]
So I'm using the Mini Stealthburner + Orbiter 2.0 and found the original klicky front cowling mount fits on the miniSB. It doesn't perfectly contour to the shape of the printhead like it does on the Afterburner, but it does seem like it would work. It shouldn't take that much adjustment to make it fit the MiniSB better.

**Comment by hubertron** [comment]
> So I'm using the Mini Stealthburner + Orbiter 2.0 and found the original klicky front cowling mount fits on the miniSB. It doesn't perfectly contour to the shape of the printhead like it does on the Afterburner, but it does seem like it would work. It shouldn't take that much adjustment to make it fit the MiniSB better.

The screwholes don't line up for my Mini-Stealth. Did you not bend or stretch anything?

**Comment by jlas1** [comment]
there is now a V0.2 version
