### ISSUE TITLE
KlickyNG_Tiny-M_mount_base and KlickyNG_Tiny-M_mount_front STEP files missing

### ISSUE THREAD

**Issue by stephane873** [jlas1/Klicky-Probe#197]
Hi, Great work! It would be wonderful if these 2 step files could be added. I am working on a below Rapido cooling duct version for EVA3

**Comment by jlas1** [comment]
It should be in the KlickyNG CAD, but i am adding them here for you
[Tiny-M.zip](https://github.com/jlas1/Klicky-Probe/files/11713559/Tiny-M.zip)

**Comment by stephane873** [comment]
I have not looked again to see if they are there but thank you so much for
adding them again.

Kind regards,
Stephane

**Comment by stephane873** [comment]
Sorry, couldn't look at this before today. The CAD models are different from the STL files.
This is what I was after:
![image](https://github.com/jlas1/Klicky-Probe/assets/28282824/d45ee6d9-ed6f-4e80-81ea-dfd8183715af)

![image](https://github.com/jlas1/Klicky-Probe/assets/28282824/42a94706-1b22-444a-bb9a-225edd9c0f97)

Wondering if these two parts are still available as CAD?

Thanks again!

**Comment by jlas1** [comment]
They are a older version of the Tiny-M mount, you can find it here https://github.com/jlas1/Klicky-Probe/blob/ee0feb4db0e103e38cf2c9d2dc630907b8796313/CAD/KlickyNGProbe_v9.step
