### ISSUE TITLE
horizontal_move_z can't be less than probe's z_offset

### ISSUE THREAD

**Issue by wolfgangmauer** [jlas1/Klicky-Probe#21]
Using klicky as z-endstop.
I do a probe_calibrate, set the z_offset = 7.300, when it should start to print i get a "horizontal_move_z can't be less than probe's z_offset" 😭 any suggestions?

....
#*# [probe]
#*# z_offset = 7.300

**Comment by wolfgangmauer** [comment]
Using "BED_MESH_CALIBRATE" in startcode was the problem.

**Comment by jlas1** [comment]
You need to increase your horizontal_move_z to be higher then 7.3mm

**Comment by wolfgangmauer** [comment]
Thanks so much!
