### ISSUE TITLE
Change macros to support minimum_cruise_ratio instead of max_accel_to_decel

### ISSUE THREAD

**Issue by Senorgif2** [jlas1/Klicky-Probe#243]
Per Klipper changes; max_accel_to_decel has been deprecated. Klicky macros provided in this depository no longer function reporting Error on "'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse"

**Comment by jlas1** [comment]
thanks, i'll check this out

**Comment by patofoto** [comment]
Same issue. Any resolution yet?.

**Comment by alexyubin** [comment]
Same issue.

**Comment by jlas1** [comment]
it's solved now, removing the setting is safe to do and won't force people to use the latest klipper version.
