### ISSUE TITLE
default_parameter_reset' is not valid in section 'gcode_macro homing_variables'

### ISSUE THREAD

**Issue by jdlarry** [jlas1/Klicky-Probe#26]
using klipper with klicky probe. when trying to connect i get this message. Need help!

**Comment by jlas1** [comment]
update to the latest version, remember to copy the variables on the beginning of the text.
Those corrections are already on the code.

**Comment by jlas1** [comment]
you can also update only that function to:

[gcode_macro _Homing_Variables]
gcode:
    {% set R  = params.RESET|default(0)  %}
    {% if R %}
        SET_GCODE_VARIABLE MACRO=_Probe_Variables VARIABLE=probe_lock VALUE={ False }
    {% endif %}

but there are more cases on the old macros that will throw that error.
