### ISSUE TITLE
Running PROBE_ACCURACY or PROBE_CALIBRATE error  

### ISSUE THREAD

**Issue by NeighNeighNeigh** [jlas1/Klicky-Probe#45]
Whenever I run a PROBE_ACCURACY or PROBE_CALIBRATE I get the following error: `Must perform … with the probe above the BED!` … Even though my probe is definitely over the bed. My probe doesn't have any wild offset values in my config:
```
[probe]
pin: PG11
x_offset: 0
y_offset: 21
```
So not sure what's going on.

**Comment by NeighNeighNeigh** [comment]
Ahhh, my bad. I had incorrect values in variable_max_bed_y and variable_max_bed_x. Sorry for being an idiot.

**Comment by jlas1** [comment]
No problem, the defaults are there for safety :-)
