### ISSUE TITLE
Small issue with "Serpa_Mini_Dragon_Cowling_wKlicky.stl"

### ISSUE THREAD

**Issue by nikolasbabetas** [jlas1/Klicky-Probe#48]
It seems like the Serpa_Mini_Dragon_Cowling_wKlicky.stl has a small defect on the bottom side. Figured I should inform you about it
![Screenshot_102](https://user-images.githubusercontent.com/95135250/149828583-5f0227df-ad9e-47e9-9b2c-6dae29c24f0c.png)

**Comment by jlas1** [comment]
solved, thanks.
![imagem](https://user-images.githubusercontent.com/16675722/149845107-4127469f-2d70-4c3d-9ac8-aef4f3889406.png)
