### ISSUE TITLE
homing_override wont do save z

### ISSUE THREAD

**Issue by Jaaannis** [jlas1/Klicky-Probe#51]
Hi,
when doing a G28 after reboot, Z do not move for a save XY homing procedure.
it seems there is an issue, where homing_override section check if it is necessary to move z for that.
Thanks for any help :-)

**Comment by jlas1** [comment]
Sorry for the lack of reply, i was without internet access, can you give me the Gcode command sequence that you use, what the printer does and what was your expectation?

**Comment by Jaaannis** [comment]
Sounds like a great time ;-)

After reboot firmware (Klipper do not know where the printhead is) with all macros included, i run a G28. 
The printer than homes X than Y after that Z.
I expected (i think it is standart in klipper for safe homing) that when I run a G28, Z Lift a bit, after that X , Y, Z home.

When as an example the klicky probe is already docked and very close to the bed it might be crash.

**Comment by jlas1** [comment]
you have a configuration to enable that behavior, variable_enable_z_hop, if set to true will move Z "up" before homing.

**Comment by Jaaannis** [comment]
Thank you ! 
From discription i never came to this.
Have a nice day
