### ISSUE TITLE
User mod listed twice

### ISSUE THREAD

**Issue by jtdowney** [jlas1/Klicky-Probe#54]
The mod from oc_geek is listed twice at https://github.com/jlas1/Klicky-Probe/tree/423d163e100aeaca21a1016b25b7a2b2cb087075/Printers/Voron/v1.8_v2.4_Legacy_Trident/Usermods with only a case change. I only noticed this because a case-insensitive filesystem threw a fit when I cloned the repo.

**Comment by jlas1** [comment]
need to check it, using windows it only shows one directory on the github client.

**Comment by jlas1** [comment]
Solved, thanks
