### ISSUE TITLE
Magnets does not fit

### ISSUE THREAD

**Issue by bjoern79de** [jlas1/Klicky-Probe#56]
You write, that I need 6x3 magnets, and they should b "below the plstic" - but when I look into the CAD files, the holes are 2.8mm deep.

**Comment by jlas1** [comment]
The holes and instructions seem to be fine, the line "Install the magnet in the Probe dock, make sure that the magnet is fully inserted, it's top should be below the plastic" is only for the probe dock, the rest of the magnets should not be inserted fully in the plastic.
