### ISSUE TITLE
Mosquito mount for Voron 0.1

### ISSUE THREAD

**Issue by DorjeDorf** [jlas1/Klicky-Probe#61]
Hi,

I know they aren't very popular, but there are still some of us out there who like our Mosquito's and want to keep using them :)

Is there any chance for a miniAB cowling version for the Mosquito with the embedded holder? I see you have one for the Dragon and BMO Dragonfly. 

The voron repo still hosts the Mosquito one. 

Thanks!

**Comment by jlas1** [comment]
Sure, point me to the CAD of the Mosquito one and i'll carve it up and put it here.

**Comment by DorjeDorf** [comment]
You actually killed me right there. I was 100% sure it was in the normal cad (there's a cowling_skeeter object), but upon double checking - it seems it's not it even though it looks like that's it. I'll double check and will update.

**Comment by DorjeDorf** [comment]
Confirmed. It's the skeeter cowling object within the regular v0.1 cad.

**Comment by jlas1** [comment]
Done, check the latest CAD and V0 STL files

**Comment by DorjeDorf** [comment]
Rockstar! I'll print it over the weekend and check it out. Can't wait! :)

**Comment by DorjeDorf** [comment]
I printed it out - looks awesome. Just one comment. 
The wall where the probe mount latches on is very thin - not like the other cowlings.

Attaching a picture that shows the Skeeter and BMO next to each other - this will show the difference. 

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/45540765/155969798-9cab19d2-8c9f-4acc-b14d-05f72a70ffb7.png">

**Comment by jlas1** [comment]
let me look into that, thanks for the feedback

**Comment by DorjeDorf** [comment]
Would be awesome, thank you. 
I also need to figure out what is different between our printers. 
I mounted what I have today - the holder is too recessed for the cowling mount to go far enough to pick up the probe. I tried simulating the mount you have on a video - it goes a touch further back, but I don't want to believe that the 3mm more would make so much of a difference.

**Comment by jlas1** [comment]
Solved

**Comment by DorjeDorf** [comment]
Awesome! Now I just have to wait for Github to show the new files ;)

**Comment by jlas1** [comment]
The files should be there already.
It was this commit https://github.com/jlas1/Klicky-Probe/commit/34d59061ca79e80f7a6e7d7539c8eba99431623d
