### ISSUE TITLE
Bed mesh -Probe triggered prior to movement-

### ISSUE THREAD

**Issue by GN1G** [jlas1/Klicky-Probe#64]
Hello,

my QGL works normal and without problems.
But if I run a Bed_Mesh_Calibration, it probes 3-4 points and then says "Probe triggered prior to movement"

Any ideas what can cause this?

best regards
GN1G

**Comment by jlas1** [comment]
Most likely a cabling issue, check the crimps of your cable.
It can also be a broken wire on the chain, go to the location that you get the "Probe triggered prior to movement" on bed mesh and do a probe_accuracy to see if you manage to trigger it.

**Comment by GN1G** [comment]
> Most likely a cabling issue, check the crimps of your cable. It can also be a broken wire on the chain, go to the location that you get the "Probe triggered prior to movement" on bed mesh and do a probe_accuracy to see if you manage to trigger it.

Thank you, I'll check it.

**Comment by DorjeDorf** [comment]
What temps are you running the mesh at? I'd assume you have your bed piping hot as well as the nozzle? 
I found that with crappier magnets, you need to drop the temp on the nozzle to 130-160C to have the magnets not be impacted by the temps and lose connectivity.

**Comment by jlas1** [comment]
I never noticed that, the magnets above more or less 80 degrees they start to lose strenght, but that is very hard to happen, at least with a silicone sock on the heat block.

**Comment by GN1G** [comment]
> What temps are you running the mesh at? I'd assume you have your bed piping hot as well as the nozzle? I found that with crappier magnets, you need to drop the temp on the nozzle to 130-160C to have the magnets not be impacted by the temps and lose connectivity.

The problem came from the stepper cable, one crimp contact was not tight so in some position it triggered the clicky probe contact.

**Comment by DorjeDorf** [comment]
> I never noticed that, the magnets above more or less 80 degrees they start to lose strenght, but that is very hard to happen, at least with a silicone sock on the heat block.

Unless you run your mesh on a bed at 100-110C and have a small dive height. Then, the combined heat can impact accuracy. Usually it appears the longer the mesh runs. I know of a couple more people who observed the same effect. We were all meshing for ABS printing so the bed was above 100C. Dropping hotend temp around 130C was enough to do a full mesh :)

But here, seems it was the cable. So good news all around ;D

**Comment by jlas1** [comment]
as it's solved, closing the issue.

**Comment by HussamAlsahafi** [comment]
> 

Which stepper motor ?
