### ISSUE TITLE
Modify Dragonfly_BMO_Cowling_wKlicky.stl for add capability sensor mod

### ISSUE THREAD

**Issue by Zal3D** [jlas1/Klicky-Probe#68]
Hello! i want combine your klicky mod with sensor mod for ERCF on my voron V0.1
Can y have .f3d or .step file of Dragonfly_BMO_Cowling_wKlicky.stl for add a small space for cables of hall sensor.

The small space is near screw of BMO hotend.

A link of filement sensor mod [https://github.com/diego589/Mini-AB-Filament-Sensor](url)

Thanks!
![klicky_sensor](https://user-images.githubusercontent.com/45119994/155732036-e8ab87ff-4a3b-4ff9-9181-1d1c64b5ecc4.png)

**Comment by jlas1** [comment]
The STEP files are all on the CAD folder, here https://github.com/jlas1/Klicky-Probe/tree/main/CAD
