### ISSUE TITLE
Probe press fit helper

### ISSUE THREAD

**Issue by Roycinger** [jlas1/Klicky-Probe#72]
Hi,

while assembling the Klicky probe, I noticed that the probe press fit helper only seems to work for the KlickyProbe_v2.stl, but not for the long and longer versions.
The 2 long / longer version wont fit into the helper

**Comment by jlas1** [comment]
There are 2 probe pressfit helper:
![image](https://user-images.githubusercontent.com/16675722/156897786-e7ef4aaf-17a3-439b-9134-fd281c1eef8b.png)

The one required for the long and longer probes is the one on the right, the STL is Longer_probe_pressfit_helper.stl

**Comment by Roycinger** [comment]
I didnt see it in the cad file. Issue is solved then :)
