### ISSUE TITLE
EVA Klicky Probe

### ISSUE THREAD

**Issue by Z3ytrox** [jlas1/Klicky-Probe#73]
When will the Klicky probe be released for EVA toolheads?

**Comment by jlas1** [comment]
There are already some versions, here https://github.com/jlas1/Klicky-Probe/tree/main/Usermods and here https://github.com/jlas1/Klicky-Probe/tree/main/Printers/Ratrig/VCore3/VCore3_STL.

**Comment by Z3ytrox** [comment]
Will these work with an ender 5 plus mercury one 1.1 setup? I will be using the EVA v2.4 on it.

**Comment by jlas1** [comment]
there is a Mercury one dedicated write up https://github.com/jlas1/Klicky-Probe/tree/main/Printers/ZeroG/Mercury_One check it out.

**Comment by Z3ytrox** [comment]
Sadly this one wont work with an rapido uhf. Any other options?
