### ISSUE TITLE
Rest mount for the DoubleT mod?

### ISSUE THREAD

**Issue by Z3ytrox** [jlas1/Klicky-Probe#77]
What mount is used for the doublet mod? Like the mount where the switch rests on when its not used.

**Comment by jlas1** [comment]
That is a good point, that info is missing.

You can use these https://github.com/jlas1/Klicky-Probe/blob/main/Printers/ZeroG/Mercury_One/Voron_Toolhead_STL/Dock_mount_Ender5.stl or even these https://github.com/jlas1/Klicky-Probe/tree/main/Printers/Voron/v1.8_v2.4_Legacy_Trident#mounting-options (with some small changes) depends on the distance from the extrusion

**Comment by Z3ytrox** [comment]
Will the first link work with the rapido uhf eva mount?

**Comment by jlas1** [comment]
maybe, it's adjustable on the z

**Comment by Z3ytrox** [comment]
But does it have enough adjustment for this?

**Comment by jlas1** [comment]
if it does not, its easy to expand.

**Comment by Z3ytrox** [comment]
Ah okay thats awesome! Does it need to be printed in abs?

**Comment by jlas1** [comment]
for dev and open printer, no. for an enclosured printer, it would be better

**Comment by Z3ytrox** [comment]
Ah okay thats understandable. So petg is prefered over pla then? I want to check it with petg first before I let someone print it in abs for me.

**Comment by jlas1** [comment]
PETG should be enough for testing, for long term usage, ABS is more tested and it works.
