### ISSUE TITLE
problem using macros

### ISSUE THREAD

**Issue by nikpoz** [jlas1/Klicky-Probe#78]
Hi all,
I am trying to setup a klicky probe on an ender 3 style printer.
When I try to use the macros I'm getting this error:
Error evaluating 'gcode_macro Attach_Probe:gcode': UndefinedError: 'dict object' has no attribute 'safe_z'
Any tips on what I'm missing here??

Thanks in advance.

**Comment by jlas1** [comment]
Do you have discord, easier to chat, ny handle is JosAr#0517

**Comment by nikpoz** [comment]
> 

Yeap, I did..
here it is, please check if I did anything silly..
[klicky-variables.zip](https://github.com/jlas1/Klicky-Probe/files/8354131/klicky-variables.zip)

**Comment by jlas1** [comment]
Easy fix, you commented safe_z:
#variable_safe_z:         	    25    # Minimum Z for attach/dock and homing functions

This needs to be uncommented, if you want it to be disabled, set "variable_enable_z_hop:        False".
Can you post a picture of your dock, i always suspect when people set variable_docklocation_z.

**Comment by nikpoz** [comment]
> Easy fix, you commented safe_z: #variable_safe_z: 25 # Minimum Z for attach/dock and homing functions
> 
> This needs to be uncommented, if you want it to be disabled, set "variable_enable_z_hop: False". Can you post a picture of your dock, i always suspect when people set variable_docklocation_z.

Ohh I missed that!! Really thanks

**Comment by jlas1** [comment]
@nikpoz when you are ready, show me your setup, it might be interesting for the usermods.

**Comment by nikpoz** [comment]
> @nikpoz when you are ready, show me your setup, it might be interesting for the usermods.

Deal!! enough more things to work on, but I'll will post my setup.
