### ISSUE TITLE
Need additional Nozzle Location Save in Probe_Calibrate

### ISSUE THREAD

**Issue by TechnicalMacaroon** [jlas1/Klicky-Probe#80]
This could use an additional save_gcode_state original_nozzle_location in the probe_calibrate macro. Specifically between the _probe_calibrate and dock_probe lines.  I was getting an error from klipper because the nozzle wasn't in the expected location after starting the calibrate command.

**Comment by jlas1** [comment]
Can you post your error, the probe_calibrate is very picky about unexpected toolhead moves during calibration.

**Comment by TechnicalMacaroon** [comment]
My printer is currently down waiting for replacement parts but once they come in I'll re-edit my config and run it again to get you the exact error.
