### ISSUE TITLE
LGX Lite

### ISSUE THREAD

**Issue by ModMike** [jlas1/Klicky-Probe#87]
Can you add an LGX Lite mount to the V0.1 mix? Preferably one that works wit the existing carriage mount so we can use the metal ones and/or avoid having to re-belt the the printer?

Thank you.

**Comment by jlas1** [comment]
Can you point me to the LGX Lite cowling that you are referring to?
The only one i know already has support for the integrated Klicky.

**Comment by ModMike** [comment]
[Here you go](https://github.com/camerony/VoronCustom/tree/main/MiniASLGXerpaLiteMount). I don't like that back plate and was hoping to integrate with the metal [V0.1 MGNC carriage mount](https://www.aliexpress.com/item/1005003448901997.html?spm=a2g0o.order_list.0.0.21ef18027ZT92O). 

I may take a crack at it myself but I think it would be nice to include and LGX lite extruder option in your GitHub.

**Comment by jlas1** [comment]
I believe that that cowling is already in the repository, here https://github.com/jlas1/Klicky-Probe/blob/main/Printers/Voron/v0/v0_STL/Serpa_Mini_Dragon_Cowling_wKlicky.stl.
The LGX mount on top of it needs no modification.

**Comment by jlas1** [comment]
gonna close this issue.

**Comment by ModMike** [comment]
I went ahead and redesigned it the way I wanted. Thanks for blazing the trail!
![Head v42](https://user-images.githubusercontent.com/36581178/164915885-3c7375ad-4e9c-49ae-a167-ff954c587409.png)

**Comment by jlas1** [comment]
Great that it worked out for you, with what probe did you end up using, i don't see the integrated klicky cutout on that image.

**Comment by ModMike** [comment]
I went with my custom version of the zero click. Much smaller and cleaner all around.

![Head v42](https://user-images.githubusercontent.com/36581178/164916157-f48b579c-0705-4646-95d1-591398376ffd.png)

**Comment by jlas1** [comment]
looks good, thanks for the feedback.

**Comment by ModMike** [comment]
Thank you for all your hard work. I would never had been able to do this without everything you did before.

**Comment by GadgetAngel** [comment]
> I went with my custom version of the zero click. Much smaller and cleaner all around.
> 
> ![Head v42](https://user-images.githubusercontent.com/36581178/164916157-f48b579c-0705-4646-95d1-591398376ffd.png)

Where do you have this on the web?

**Comment by ModMike** [comment]
It's not released yet. I'm still testing. I just finished printing my first set and am making adjustments. I will post when done.

**Comment by ModMike** [comment]
In Beta, a few people printing, will release next weekend.

![ModMike Slick Toolhead for V0 1 v79](https://user-images.githubusercontent.com/36581178/165884323-1bd18f1b-9160-418c-b532-0eaa4ffbac2e.png)

**Comment by Rhastlyn** [comment]
> In Beta, a few people printing, will release next weekend.
> 
> ![ModMike Slick Toolhead for V0 1 v79](https://user-images.githubusercontent.com/36581178/165884323-1bd18f1b-9160-418c-b532-0eaa4ffbac2e.png)

Need any additional testers?  I'm thinking of this configuration for a rebuild and this looks promising!
