### ISSUE TITLE
No wires needed for V-Core 3 probe.

### ISSUE THREAD

**Issue by bullwinkle3000** [jlas1/Klicky-Probe#95]
In the instructions for the V-Core 3 version of the probe kit, you say:

"Then take your self tapping screws and screw the microswitch in place, you should also now solder the wires to the outside pins of the switch, that way making this a Normally Connected probe."

These instructions are similar for the other probes, where the probe pins are somewhat distant from the magnets and wire is needed to connect.

But, in this version, the outside pins of the probe are already snug against the magnets, right?  There are no wires to solder here, unless very short wires to ensure better connection?

**Comment by dmason1992** [comment]
You are correct! This is a documentation error that needs fixing
