### ISSUE TITLE
Voron 0 Revo Cowling

### ISSUE THREAD

**Issue by jplekkerkerker** [jlas1/Klicky-Probe#97]
Will there be a Voron 0.1 Revo Cowling with integrated klicky-mount?

**Comment by jlas1** [comment]
yeah, as soon as it's released, or has it been already?

**Comment by Grooviee** [comment]
It's released on the Voron 0-github: https://github.com/VoronDesign/Voron-0/tree/Voron0.1/STLs/Toolheads/Mini_Afterburner/Revo_Voron_Toolhead_DD

**Comment by jlas1** [comment]
There is no CAD, without that, i cannot do a klicky version.

**Comment by Munkee82** [comment]
https://e3d-online.zendesk.com/hc/en-us/articles/4444939320093-Revo-Voron-Reference-CAD

**Comment by jlas1** [comment]
that is the hotend cad, I need the cowling cad for the v0. 1.

**Comment by Munkee82** [comment]
This one?
https://github.com/KurioHonoo/Mini-AfterSherpa/blob/main/CAD/MiniAS_Revo_Voron_Base.step

**Comment by jlas1** [comment]
This is for the AfterSherpa, but i can mod that one.

**Comment by Munkee82** [comment]
That would be cool.  I use the mini AS anyway.
