### ISSUE TITLE
Docking issue

### ISSUE THREAD

**Issue by rmilyard** [jlas1/Klicky-Probe#99]
I could use some ideas what look for on this.  The v2.4 was printing fine and all worked.  I updated all my file moonraker, klipper and z_calobration.  So after that looks like now when tried to dock probe is drops down to far.  Did something change I need to look for?   https://share.icloud.com/photos/0c63r2jqQNJtYrYf1V1DQnlfg
[iCloud.com](https://share.icloud.com/photos/0c63r2jqQNJtYrYf1V1DQnlfg)

**Comment by jlas1** [comment]
will close this, in the end @rmilyard needed to dock 2mm closer to X0, for some reason.
